// Package protocol defines the length-prefixed JSON wire format used for all
// host<->guest RPC over the virtio-vsock channel.
//
// Frame layout on the wire:
//
//	┌───────────────────────┬──────────────────────────────────────────┐
//	│ 4-byte big-endian u32  │ JSON-encoded message of exactly N bytes  │
//	│   payload length (N)   │                                          │
//	└───────────────────────┴──────────────────────────────────────────┘
//
// Protocol exchange: the host opens a vsock connection and writes exactly one
// ExecutionRequest. The guest replies with a stream of ResponseFrame messages —
// zero or more Output frames, then exactly one terminal frame (Exit, Error, or
// Pong) — and closes the connection. One request per connection keeps framing
// trivial and avoids head-of-line blocking between concurrent executions.
//
// This package is OS-independent and compiles on every platform, so it can be
// unit-tested without a Linux/KVM host.
package protocol

import (
	"encoding/binary"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"sync"
)

// MaxFrameSize bounds a single wire frame. A 4-byte length prefix can describe
// up to 4 GiB; without a cap a malicious or buggy peer could make us allocate
// that much from one header (a trivial memory-DoS). 16 MiB is comfortably larger
// than any legitimate script or output chunk.
const MaxFrameSize = 16 << 20 // 16 MiB

// DefaultPort is the guest-side vsock port the agent listens on.
const DefaultPort uint32 = 5005

// Sentinel errors callers can match with errors.Is.
var (
	ErrFrameTooLarge = errors.New("protocol: frame exceeds maximum size")
)

// RequestKind enumerates the operations the host may ask the guest to perform.
type RequestKind string

const (
	KindExec RequestKind = "exec" // run a shell script
	KindPing RequestKind = "ping" // liveness probe (heartbeat)
)

// ExecutionRequest is the single message the host writes after connecting.
type ExecutionRequest struct {
	// ID correlates a request with its response frames. Generated by the host.
	ID string `json:"id"`
	// Kind selects the operation. Empty is treated as KindExec for convenience.
	Kind RequestKind `json:"kind,omitempty"`
	// Script is the program executed by `<shell> -c` when Kind==exec.
	Script string `json:"script,omitempty"`
	// TimeoutSec bounds wall-clock execution. <=0 means the agent default.
	TimeoutSec int `json:"timeout_sec,omitempty"`
	// Workdir overrides the working directory. Empty means the agent default
	// (the locked-down /workspace directory).
	Workdir string `json:"workdir,omitempty"`
	// Env supplies extra environment variables. The agent always starts from a
	// minimal, sanitized base environment.
	Env map[string]string `json:"env,omitempty"`
}

// FrameKind enumerates the response-frame variants streamed back by the guest.
type FrameKind string

const (
	FrameOutput FrameKind = "output" // merged stdout+stderr chunk
	FrameExit   FrameKind = "exit"   // terminal: process finished
	FrameError  FrameKind = "error"  // terminal: agent-level failure
	FramePong   FrameKind = "pong"   // terminal: ping reply
)

// ResponseFrame is one message in the guest->host response stream.
type ResponseFrame struct {
	ID       string    `json:"id"`
	Kind     FrameKind `json:"kind"`
	Data     string    `json:"data,omitempty"`      // output bytes (FrameOutput)
	ExitCode int       `json:"exit_code,omitempty"` // process exit code (FrameExit)
	Error    string    `json:"error,omitempty"`     // error detail (FrameError)
}

// Terminal reports whether a frame ends the response stream.
func (f ResponseFrame) Terminal() bool {
	switch f.Kind {
	case FrameExit, FrameError, FramePong:
		return true
	default:
		return false
	}
}

// WriteMessage encodes v as JSON and writes a single length-prefixed frame to w.
// Concurrent callers on one connection must serialize through a FrameWriter; a
// raw io.Writer is not safe for concurrent WriteMessage calls.
func WriteMessage(w io.Writer, v any) error {
	payload, err := json.Marshal(v)
	if err != nil {
		return fmt.Errorf("protocol: marshal: %w", err)
	}
	if len(payload) > MaxFrameSize {
		return ErrFrameTooLarge
	}
	var hdr [4]byte
	binary.BigEndian.PutUint32(hdr[:], uint32(len(payload)))
	if _, err := w.Write(hdr[:]); err != nil {
		return fmt.Errorf("protocol: write header: %w", err)
	}
	if _, err := w.Write(payload); err != nil {
		return fmt.Errorf("protocol: write payload: %w", err)
	}
	return nil
}

// ReadMessage reads one length-prefixed frame from r and unmarshals it into v.
// The length prefix is validated against MaxFrameSize before any allocation.
// io.EOF / io.ErrUnexpectedEOF are returned unwrapped so callers can detect a
// closed connection with errors.Is.
func ReadMessage(r io.Reader, v any) error {
	var hdr [4]byte
	if _, err := io.ReadFull(r, hdr[:]); err != nil {
		return err
	}
	n := binary.BigEndian.Uint32(hdr[:])
	if n > MaxFrameSize {
		return ErrFrameTooLarge
	}
	payload := make([]byte, n)
	if _, err := io.ReadFull(r, payload); err != nil {
		return fmt.Errorf("protocol: read payload: %w", err)
	}
	if err := json.Unmarshal(payload, v); err != nil {
		return fmt.Errorf("protocol: unmarshal: %w", err)
	}
	return nil
}

// FrameWriter serializes concurrent WriteMessage calls on one connection. The
// guest agent may emit output and terminal frames from different goroutines, so
// a mutex keeps frames from interleaving on the wire.
type FrameWriter struct {
	mu sync.Mutex
	w  io.Writer
}

// NewFrameWriter wraps w so frames written from multiple goroutines stay intact.
func NewFrameWriter(w io.Writer) *FrameWriter {
	return &FrameWriter{w: w}
}

// Write sends a single frame, holding the lock across header+payload.
func (fw *FrameWriter) Write(v any) error {
	fw.mu.Lock()
	defer fw.mu.Unlock()
	return WriteMessage(fw.w, v)
}
